apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: traefik
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.foodonline.run.place
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-service
  namespace: traefik
spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`grafana.foodonline.run.place`)
      kind: Rule

      middlewares:
        - name: redirect-to-https 
          namespace: traefik

      services:
        - name: monitoring-grafana
          namespace: monitoring
          port: 80

  tls:
    secretName: grafana-tls
