apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: foodonline-tls
  namespace: default

spec:
  secretName: foodonline-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - foodonline.run.place
